version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: paymentdb
    restart: always
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment:
    build: payment/.
    container_name: payment-api
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres@123
    ports:
      - "8080:8080"

volumes:
  postgres_data: